source 'https://rubygems.org'

gem 'pry-rails'

gem 'annotate'

# The Addressable gem makes it easy to construct URLs. Always prefer a
# tool like it over manually creating URLs via string interpolation.
# Certain characters are not permitted in URLs and so have to be escaped
# properly. This isn't something you want to have to worry about.
gem 'addressable'

# The RestClient gem provides a simple interface for making HTTP requests,
# providing methods like ::get, ::post, ::put, ::patch, and ::delete.
# : RestClient will throw an exception when it receives a response
# from a request that is not 200-OK. This doesn't necessarily mean that
# your code is wrong. It means either the request is wrong or your
# Rails code is wrong. When you get a non-200 response check the Rails
# logs first to see if something went wrong on the Rails side.
gem 'rest-client'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.7.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
